services:
  backend:
    build: ./back
    container_name: preytweet-backend
    env_file:
      - ./back/.env
    ports:
      - "8000:8000"

  socket:
    build: ./SocketConn
    container_name: preytweet-socket
    env_file:
      - ./SocketConn/.env
    ports:
      - "9000:9000"